# Generated by Django 4.1.7 on 2023-03-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exercicio', models.CharField(max_length=800, verbose_name='Nome Exercício')),
                ('serie', models.CharField(blank=True, max_length=800, verbose_name='Seríe')),
                ('descanso', models.CharField(blank=True, max_length=800, verbose_name='Descanso')),
                ('parte_corpo', models.CharField(choices=[('BR', 'Braço'), ('CT', 'Costas'), ('PE', 'Perna'), ('PT', 'Peito'), ('AB', 'Abdomem')], max_length=2)),
            ],
            options={
                'db_table': 'exercicio',
                'ordering': ['-id'],
            },
        ),
    ]
