# Generated by Django 4.1.7 on 2023-03-16 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixa', '0001_initial'),
        ('exercicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='fixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fixa.fixa', verbose_name='Fixa'),
        ),
    ]
