# Generated by Django 4.1.7 on 2023-03-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dia')),
                ('nome', models.CharField(max_length=800, verbose_name='Nome Treino')),
                ('obs', models.CharField(max_length=800, verbose_name='Observação')),
            ],
            options={
                'db_table': 'fixa',
                'ordering': ['-id'],
            },
        ),
    ]
